### PR TITLE
BL-1052: Index new location_facet field.

### PR DESCRIPTION
**Pull request by dkinzer**
We need this to create our library/location pivot table.

### CODE REVIEW

**Review by sensei100 — COMMENTED** [review]
@dkinzer Are you sure this is supposed to be done at the holding level?  I think item level locations would be more accurate.  That is where we get availability locations from.

**Review by quoideneuf — APPROVED** [review]

**Comment by bibliotechy** [comment]
@sensei100 @dkinzer seems like the real question is: Can a holding record's items each have a different location? Or would that be another holding record at that point. Probably a question for the metadata team.

If all items of a holding are always in the same location, then this seems fine. If they can vary within a holding,then @sensei100 is right and we'd need to do this at the item level

**Comment by sensei100** [comment]
I'm pretty sure an item can be in multiple locations.  And I think that we are supposed to use the temporary location (if assigned) and I'm pretty sure that only comes from the item level.

**Comment by bibliotechy** [comment]
@sensei100 yeah, you are right, I just read the comments on the ticket, and that makes a lot of sense.

**Comment by dkinzer** [comment]
OK @sensei100,  I'll update that to be item level location.

**Comment by dkinzer** [comment]
@sensei100 @bibliotechy though, to be honest, I don't understand why we are using Holding location for location_display field?  I basically just copied pasted that field definition for the facet.  Should that be changed too?

**Comment by sensei100** [comment]
@dkinzer location_display should probably be removed.  I don't see anywhere in tul_cob where we actually use that.  We just need to make sure we include the fields for temporary(current) location and permanent location. I'm pretty sure they are subfields e and g.

**Comment by bibliotechy** [comment]
@dkinzer @sensei100 my lingering question is the requirements in the JIRA  about the special handling of BookBot items

> For BookBot locations: Currently, we use the label “Charles Library” for the BookBot “Library” facet. For all locations that appear under the BookBot library code, we should use the label “BookBot” rather than differentiating between them.

Feels like we would need custom logic to handle that, or am I wrong?

**Comment by dkinzer** [comment]
@sensei100 OK.  We're doing some really funky things with the items_json_display logic .. including getting library/location for holdings without items, which is a thing.  We don't apply the same logic for getting library 🤔, so that's interesting too..

**Comment by dkinzer** [comment]
@bibliotechy I was always planning to do some basic logic cob side for label/display ... I assumed this would have to be done no matter what.

**Comment by bibliotechy** [comment]
@dkinzer but if these values are in the facet area, we can't merge them afterwards. So even if we label all of them "Bookbot"  cob-side, wouldn't that leave us with multiple "Bookbot" values with different numbers of hits?

**Comment by dkinzer** [comment]
@bibliotechy. I think from my local experiments that it should be OK, one single bookbot location will appear under  Charlse Library  once we filter out non Charlse Library bookbot locations.  We have he same issue with any location because of the many to many relationship.  But the numbers work out correctly once you just filter out by library.

**Comment by dkinzer** [comment]
@sensei100, @bibliotechy I updated to use the similar logic as we currently use for library (item).

**Review by bibliotechy — APPROVED** [review]

**Comment by bibliotechy** [comment]
@dkinzer I'm satisfied with that changes if @sensei100  is as well.

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
