### PR TITLE
BL-1524: Index donor info display field.

### PR DESCRIPTION
**Pull request by dkinzer**
* Add donor_inf_display field
* Use built-in translation mechanism to transform mmsid to donor_info

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer Where are we going to store the data for this field?  I know that with the Hathi data, we added it to this repo.  I'm just curious what the plan.

**Comment by dkinzer** [comment]
@sensei100 I'm hoping that we will store this data as a translation map in lib/translation_maps/donor_info.yaml

**Comment by sensei100** [comment]
@dkinzer That work will happen in a separate PR?

**Comment by dkinzer** [comment]
@sensei100 that work is happening in a separate PR ... this work was just to get the stub setup.

**Comment by dkinzer** [comment]
It's part of this ticket: https://tulibdev.atlassian.net/browse/BL-1525

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
